urdf_path: urdf/AzureLoong_sr.urdf
wo_controller: false
robot_name: OpenLoong
base_pose:
  position: [0, 0, 0.9]
  orientation: [0, 0, 0.707, 0.707]
arms:
- joint_index: [4, 5, 6, 7, 8, 9, 10]
  ee_index: 12
  rest_j_pos: [0.20, -0.97, -2.00, 1.70, 0.63, 0.00, -0.43]
- joint_index: [41, 42, 43, 44, 45, 46, 47]
  ee_index: 49
  rest_j_pos:  [-0.20, -0.97, 2.00, 1.70, -0.63, 0.00, 0.43]
grippers:
- joint_index: [36, 37, 38, 15, 16, 17, 20, 21, 22, 25, 26, 27, 31, 32, 33]
- joint_index: [74, 75, 76, 53, 54, 55, 58, 59, 60, 63, 64, 65, 69, 70, 71]
head: 
 joint_index: [-1, 3, 2]
 rest_j_pos: [-1, 0, 0]
controller_indices:
  cmd_ee: [12, 49]
  base: [1, 1]
vibration_thresholds:
  ee_dist: [0.15, 0.2]
  tabletop_height: 0.85